#!/bin/bash

UNO="/bin/uname.origin"

rel="2.6.32-504.16.2.el6.x86_64"
sys="Linux"
mac=`$UNO -m`
pro=`$UNO -p`
hwd=`$UNO -i`
osy=`$UNO -o`
ver=`$UNO -v`
if test "x$1" = "x-r" ; then
  echo "$rel"
elif test "x$1" = "x-s" ; then
  echo "$sys"
elif test "x$1" = "x-m" ; then
  echo "$mac"
elif test "x$1" = "x-a" ; then
  echo "$sys $HOSTNAME $rel $ver $mac $pro $hwd $osy"
else
  $UNO $1
fi

